-- This migration originally duplicated schema objects introduced by
-- earlier migrations and caused `prisma migrate deploy` failures on clean
-- environments (duplicate enum/table creation).
--
-- Intentionally left empty to preserve linear migration history while
-- keeping deploys deterministic.
